URL = "https://automated.pythonanywhere.com/login/"
URL2 = "https://automated.pythonanywhere.com/"
ID_ONE = "id_username"
ID_TWO = "id_password"
CRED = "automated"
BY_ONE = "id"
BY_TWO = "xpath"
TO_SCRAPE = "/html/body/div[1]/div/h1[2]"
